name: Build Vanilla+ Launcher EXE

on:
  push:
    branches: [ main ] # Se activa en cada push a la rama main
  workflow_dispatch: # Permite la ejecuci√≥n manual

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Download Icon
      run: curl -L "https://github.com/Kewz4/k-launcher-code/raw/main/Kewz%20Launcher.ico" -o "Kewz Launcher.ico"
      shell: bash

    - name: Build the application
      run: |
        pyinstaller --onefile --windowed --name "Kewz Launcher" --icon "Kewz Launcher.ico" `
          --hidden-import="launcher_ui" `
          --hidden-import="music_player" `
          --hidden-import="webview.platforms.winforms" `
          --hidden-import="webview.platforms.edgechromium" `
          --hidden-import="win32gui" `
          --hidden-import="win32con" `
          --hidden-import="psutil" `
          --hidden-import="pycaw" `
          --hidden-import="comtypes" `
          launcher_main.py

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Kewz-Launcher-EXE
        path: dist/Kewz Launcher.exe
